# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import calculator_pb2 as calculator__pb2


class CloudCalculatorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.compute = channel.unary_unary(
                '/endpoints.calculator.CloudCalculator/compute',
                request_serializer=calculator__pb2.ComputationRequest.SerializeToString,
                response_deserializer=calculator__pb2.ComputationResponse.FromString,
                )


class CloudCalculatorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def compute(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CloudCalculatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'compute': grpc.unary_unary_rpc_method_handler(
                    servicer.compute,
                    request_deserializer=calculator__pb2.ComputationRequest.FromString,
                    response_serializer=calculator__pb2.ComputationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'endpoints.calculator.CloudCalculator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CloudCalculator(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def compute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/endpoints.calculator.CloudCalculator/compute',
            calculator__pb2.ComputationRequest.SerializeToString,
            calculator__pb2.ComputationResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
