# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: calculator.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='calculator.proto',
  package='endpoints.calculator',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10\x63\x61lculator.proto\x12\x14\x65ndpoints.calculator\"{\n\x12\x43omputationRequest\x12\x13\n\x0b\x66irstNumber\x18\x01 \x01(\x02\x12\x14\n\x0csecondNumber\x18\x02 \x01(\x02\x12:\n\toperation\x18\x03 \x01(\x0e\x32\'.endpoints.calculator.ComputeOperations\"i\n\x13\x43omputationResponse\x12\x15\n\rresponseValue\x18\x01 \x01(\x02\x12;\n\x0eresponseStatus\x18\x02 \x01(\x0e\x32#.endpoints.calculator.ComputeStatus*D\n\x11\x43omputeOperations\x12\x07\n\x03\x41\x44\x44\x10\x00\x12\x0c\n\x08SUBTRACT\x10\x01\x12\x0c\n\x08MULTIPLY\x10\x02\x12\n\n\x06\x44IVIDE\x10\x03*\x89\x01\n\rComputeStatus\x12\x18\n\x14OPERATION_SUCCESSFUL\x10\x00\x12\x15\n\x11UNKNOWN_OPERATION\x10\x01\x12\x15\n\x11ILLEGAL_OPERATION\x10\x02\x12\x1a\n\x16OPERATION_UNSUCCESSFUL\x10\x03\x12\x14\n\x10INCORRECT_FORMAT\x10\x04\x32q\n\x0f\x43loudCalculator\x12^\n\x07\x63ompute\x12(.endpoints.calculator.ComputationRequest\x1a).endpoints.calculator.ComputationResponseb\x06proto3'
)

_COMPUTEOPERATIONS = _descriptor.EnumDescriptor(
  name='ComputeOperations',
  full_name='endpoints.calculator.ComputeOperations',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ADD', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SUBTRACT', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MULTIPLY', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DIVIDE', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=274,
  serialized_end=342,
)
_sym_db.RegisterEnumDescriptor(_COMPUTEOPERATIONS)

ComputeOperations = enum_type_wrapper.EnumTypeWrapper(_COMPUTEOPERATIONS)
_COMPUTESTATUS = _descriptor.EnumDescriptor(
  name='ComputeStatus',
  full_name='endpoints.calculator.ComputeStatus',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='OPERATION_SUCCESSFUL', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN_OPERATION', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ILLEGAL_OPERATION', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='OPERATION_UNSUCCESSFUL', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='INCORRECT_FORMAT', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=345,
  serialized_end=482,
)
_sym_db.RegisterEnumDescriptor(_COMPUTESTATUS)

ComputeStatus = enum_type_wrapper.EnumTypeWrapper(_COMPUTESTATUS)
ADD = 0
SUBTRACT = 1
MULTIPLY = 2
DIVIDE = 3
OPERATION_SUCCESSFUL = 0
UNKNOWN_OPERATION = 1
ILLEGAL_OPERATION = 2
OPERATION_UNSUCCESSFUL = 3
INCORRECT_FORMAT = 4



_COMPUTATIONREQUEST = _descriptor.Descriptor(
  name='ComputationRequest',
  full_name='endpoints.calculator.ComputationRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='firstNumber', full_name='endpoints.calculator.ComputationRequest.firstNumber', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='secondNumber', full_name='endpoints.calculator.ComputationRequest.secondNumber', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='operation', full_name='endpoints.calculator.ComputationRequest.operation', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=165,
)


_COMPUTATIONRESPONSE = _descriptor.Descriptor(
  name='ComputationResponse',
  full_name='endpoints.calculator.ComputationResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='responseValue', full_name='endpoints.calculator.ComputationResponse.responseValue', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='responseStatus', full_name='endpoints.calculator.ComputationResponse.responseStatus', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=167,
  serialized_end=272,
)

_COMPUTATIONREQUEST.fields_by_name['operation'].enum_type = _COMPUTEOPERATIONS
_COMPUTATIONRESPONSE.fields_by_name['responseStatus'].enum_type = _COMPUTESTATUS
DESCRIPTOR.message_types_by_name['ComputationRequest'] = _COMPUTATIONREQUEST
DESCRIPTOR.message_types_by_name['ComputationResponse'] = _COMPUTATIONRESPONSE
DESCRIPTOR.enum_types_by_name['ComputeOperations'] = _COMPUTEOPERATIONS
DESCRIPTOR.enum_types_by_name['ComputeStatus'] = _COMPUTESTATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ComputationRequest = _reflection.GeneratedProtocolMessageType('ComputationRequest', (_message.Message,), {
  'DESCRIPTOR' : _COMPUTATIONREQUEST,
  '__module__' : 'calculator_pb2'
  # @@protoc_insertion_point(class_scope:endpoints.calculator.ComputationRequest)
  })
_sym_db.RegisterMessage(ComputationRequest)

ComputationResponse = _reflection.GeneratedProtocolMessageType('ComputationResponse', (_message.Message,), {
  'DESCRIPTOR' : _COMPUTATIONRESPONSE,
  '__module__' : 'calculator_pb2'
  # @@protoc_insertion_point(class_scope:endpoints.calculator.ComputationResponse)
  })
_sym_db.RegisterMessage(ComputationResponse)



_CLOUDCALCULATOR = _descriptor.ServiceDescriptor(
  name='CloudCalculator',
  full_name='endpoints.calculator.CloudCalculator',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=484,
  serialized_end=597,
  methods=[
  _descriptor.MethodDescriptor(
    name='compute',
    full_name='endpoints.calculator.CloudCalculator.compute',
    index=0,
    containing_service=None,
    input_type=_COMPUTATIONREQUEST,
    output_type=_COMPUTATIONRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_CLOUDCALCULATOR)

DESCRIPTOR.services_by_name['CloudCalculator'] = _CLOUDCALCULATOR

# @@protoc_insertion_point(module_scope)
