# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import calculator_pb2 as calculator__pb2


class CloudCalculatorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.compute = channel.unary_unary(
                '/endpoints.calculator.CloudCalculator/compute',
                request_serializer=calculator__pb2.ComputationRequest.SerializeToString,
                response_deserializer=calculator__pb2.ComputationResponse.FromString,
                )


class CloudCalculatorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def compute(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CloudCalculatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'compute': grpc.unary_unary_rpc_method_handler(
                    servicer.compute,
                    request_deserializer=calculator__pb2.ComputationRequest.FromString,
                    response_serializer=calculator__pb2.ComputationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'endpoints.calculator.CloudCalculator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CloudCalculator(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def compute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/endpoints.calculator.CloudCalculator/compute',
            calculator__pb2.ComputationRequest.SerializeToString,
            calculator__pb2.ComputationResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)


class CloudLoginStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.create_account = channel.unary_unary(
                '/endpoints.calculator.CloudLogin/create_account',
                request_serializer=calculator__pb2.CreateAccountRequest.SerializeToString,
                response_deserializer=calculator__pb2.CreateAccountResponse.FromString,
                )
        self.login = channel.unary_unary(
                '/endpoints.calculator.CloudLogin/login',
                request_serializer=calculator__pb2.LoginRequest.SerializeToString,
                response_deserializer=calculator__pb2.LoginResponse.FromString,
                )
        self.terminateAccount = channel.unary_unary(
                '/endpoints.calculator.CloudLogin/terminateAccount',
                request_serializer=calculator__pb2.terminateRequest.SerializeToString,
                response_deserializer=calculator__pb2.terminateResponse.FromString,
                )
        self.refresh = channel.unary_unary(
                '/endpoints.calculator.CloudLogin/refresh',
                request_serializer=calculator__pb2.RefreshRequest.SerializeToString,
                response_deserializer=calculator__pb2.RefreshResponse.FromString,
                )


class CloudLoginServicer(object):
    """Missing associated documentation comment in .proto file."""

    def create_account(self, request, context):
        """@Brief Creates a user account in the firestore database
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def login(self, request, context):
        """@Brief Attempts to log a user in
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def terminateAccount(self, request, context):
        """@brief Deletes a user from the database
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def refresh(self, request, context):
        """@brief Processes a refresh request
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CloudLoginServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'create_account': grpc.unary_unary_rpc_method_handler(
                    servicer.create_account,
                    request_deserializer=calculator__pb2.CreateAccountRequest.FromString,
                    response_serializer=calculator__pb2.CreateAccountResponse.SerializeToString,
            ),
            'login': grpc.unary_unary_rpc_method_handler(
                    servicer.login,
                    request_deserializer=calculator__pb2.LoginRequest.FromString,
                    response_serializer=calculator__pb2.LoginResponse.SerializeToString,
            ),
            'terminateAccount': grpc.unary_unary_rpc_method_handler(
                    servicer.terminateAccount,
                    request_deserializer=calculator__pb2.terminateRequest.FromString,
                    response_serializer=calculator__pb2.terminateResponse.SerializeToString,
            ),
            'refresh': grpc.unary_unary_rpc_method_handler(
                    servicer.refresh,
                    request_deserializer=calculator__pb2.RefreshRequest.FromString,
                    response_serializer=calculator__pb2.RefreshResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'endpoints.calculator.CloudLogin', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CloudLogin(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def create_account(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/endpoints.calculator.CloudLogin/create_account',
            calculator__pb2.CreateAccountRequest.SerializeToString,
            calculator__pb2.CreateAccountResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/endpoints.calculator.CloudLogin/login',
            calculator__pb2.LoginRequest.SerializeToString,
            calculator__pb2.LoginResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def terminateAccount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/endpoints.calculator.CloudLogin/terminateAccount',
            calculator__pb2.terminateRequest.SerializeToString,
            calculator__pb2.terminateResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def refresh(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/endpoints.calculator.CloudLogin/refresh',
            calculator__pb2.RefreshRequest.SerializeToString,
            calculator__pb2.RefreshResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
